### ISSUE TITLE
Add stubs for these fluid operations

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#12]
- OP_SWAP_SOVEREIGN_ADDRESS
- OP_UPDATE_FEES
- OP_FREEZE_ADDRESS
- OP_RELEASE_ADDRESS

**Comment by ghost** [comment]
It would be OP_SWAP_SOVEREIGN_IDENTITY

**Comment by spencerlievens** [comment]
I see these stubbed.

    OP_SWAP_SOVEREIGN_ADDRESS = 0xc5,
    OP_UPDATE_FEES = 0xc6,
    OP_FREEZE_ADDRESS = 0xc7,
    OP_RELEASE_ADDRESS = 0xc8,
