### ISSUE TITLE
Request for generatetoaddress be used for production as well not just regtest?

### ISSUE THREAD

**Issue by fogoat** [duality-solutions/Dynamic#128]
Hello, I am trying to solo mine and send any mined rewards to a specific remote public key address. Dynamic says generatetoaddress is only for regtest on the console. I'm using Ubuntu 16.0.4 and would like to mine to a non-local wallet. Is this possible? 

I don't want to mine via pool.

I was able to sync the blockchain using 
`./dynamicd --daemon`
`setgenerate true 4`
`getgenerate` shows 400% CPU usage

I'm just wondering why `generatetoaddress` is only for regtest. If this coin is GPU & ASIC resistant, seems like solo CPU mining with a remote address is reasonable use case.

**Comment by Duality-CDOO** [comment]
If you look deeper into the generatetoaddress code, you will see it is for creating DYN on the fly to an address in RegTest. It is for testing purposes only.

**Comment by fogoat** [comment]
Hi, thanks for your response. Yes, I didn't check the code but I understand what the error message means. I should revise my question to ask if `generatetoaddress` couldn be opened up for production use? I've used the `generatetoaddress` command with other cpu friendly altcoins before.

**Comment by Duality-CDOO** [comment]
It cannot be opened up for production use as the function stands.
