### ISSUE TITLE
Yiimp, algo agron2d

### ISSUE THREAD

**Issue by goodthebest** [duality-solutions/Dynamic#129]
Many folks want to mine DYN with yiimp. Could you please integrate algo argon2d with yiimp, you might like to place a pull request 

https://github.com/goodthebest/yiimp

**Comment by goodthebest** [comment]
@AmirAbrams I'm still waiting for an update for argon2d implementation on yiimp? You canceled some pull requests, any progress? I want to test it as soon as get a nod from you.

**Comment by Duality-CDOO** [comment]
Closed? Does this work?
