### ISSUE TITLE
random Windows Qt crash

### ISSUE THREAD

**Issue by SvenKercher** [duality-solutions/Dynamic#131]
### Describe the issue
Windows Qt Wallet crash
Related to both , AVX2 and normal Version

During Sync (fresh and also when only a few hrs are left) the Qt crash
Logfile has no error at the crash
But during sync a lot of

> 2018-03-28 12:59:32 ProcessNewBlock : ACCEPTED
> 2018-03-28 12:59:32 ProcessNewBlock : ACCEPTED
> 2018-03-28 12:59:32 ProcessNewBlock : ACCEPTED
> 2018-03-28 12:59:33 ProcessNewBlock : ACCEPTED
> 2018-03-28 12:59:33 ProcessNewBlock : ACCEPTED

are in the logfile, and also several times

> 2018-03-28 12:50:14 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
> 2018-03-28 12:50:14 Unable to read from disk! Highly unlikely but has occured, may be bug or damaged blockchain copy!

Sometimes its during sync and then it continues to sync , sometimes its near the end, when the crash occures

The weird thing is that the 

> ProcessNewBlock : ACCEPTED

also is like an loop when the daemon of an dynode crash
There its only possible to solve it with disable the dynode options in conf and delete the dnpayments.dat
And after full sync then stop, enable dynode option , and start the daemon again

And what i noticed too is that the dnpayments.dat is at such an broken dynode around 2-5 times bigger then on an normal working dynode
 
### Steps to reproduce
1. 
2. 
3. 
### What platform are you using (Linux, Windows, Mac)
Win10 64 (2 Computers)
Wallet Qt v2.2.0.0 (AVX2 and normal)

**Comment by marsmensch** [comment]
Also affects linux right now. I expect the last merged pull request is directly related and we can expect a new release soon.

**Comment by AmirAbrams** [comment]
@coin-info-net and @marsmensch,

It appears to be an issue with our fluid protocol transaction verification that was triggered by the atomic BlockNet transaction on 2018-03-27 (block 26659, nTime 1522189353).  I still need to investigate what is different in block 26659 atomic BlockNet transaction that caused this issue but all other blocks do not.

This PR should fix the issue: https://github.com/duality-solutions/Dynamic/pull/133
It moves fluid transaction validity checking to a more appropriate place (from `IsFinalTx` to `ContextualCheckBlock`).  When the wallet node receives the block header for 26659, this line in `IsFinalTx` would fail and eventually cause the seg fault:

`CBlockIndex* pblockindex = chainActive[nBlockHeight-1];`

Please let me know if you still experience the segfault and errors in the debug log after this PR.

**Comment by Duality-CDOO** [comment]
Fixed with #133
