### ISSUE TITLE
RPC Error with dynode winner and current

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#148]
### Describe the issue
Running `dynode winner` or `dynode current` commands crashes the v2.3 wallet.  Not an issue in v2.2.
### Steps to reproduce
1. fully sync the blockchain and dynodes.
2. run `dynode winner` or `dynode current`
3. wallet is stuck.
### Expected behavior (tell us what should happen)
returns a valid dynode winner or current dynode.
### Actual behavior (tell us what happens instead)
wallet freezes.
### What platform are you using (Linux, Windows, Mac)
Ubuntu 16.04.

**Comment by Duality-CDOO** [comment]
Fixed in upcoming v2.3
