### ISSUE TITLE
Copy Transaction Wallet Address doe not work in Qt UI

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#157]

**Comment by AmirAbrams** [comment]
Reproduction Steps:
- In Qt wallet, go to the "Transactions" tab.  
- Select a transaction at random in the list.  
- Right click and select "Copy Address"
- Try to paste the address that was copied.

**Comment by Duality-CDOO** [comment]
Fixed - https://github.com/duality-solutions/Dynamic/commit/ec57a03047bb75434c09a50e443ea809c40c711f
