### ISSUE TITLE
Missing Korean Translations

### ISSUE THREAD

**Issue by LordDarkHelmet** [duality-solutions/Dynamic#165]
### Describe the issue
There are two known translation issues in the Command Line Options window. 
For the "-debug=<category>" translation, there is a note in init.cpp specifically asking not to translate that line.  Do we want to still translate this?
For -prune, I need the full translation. Only the first part is translated The rest of it still needs translation.

**Comment by Duality-CDOO** [comment]
In terms of the Prune translation that you need, simply use Google Translate. It isn't required that the Korean translation is perfect first time, but what is needed is that all sections translate.

Please could you reference the line for -debug that states not to translate the line.

EDIT: I see the debug text and only "or specifically:" needs translating, the translation for that is on Line 5391:

<img width="632" alt="screen shot 2018-06-20 at 11 36 39" src="https://user-images.githubusercontent.com/36229929/41650407-41799cf8-747e-11e8-8bee-e52e882b108e.png">

Also this needs translating:

<img width="632" alt="screen shot 2018-06-20 at 11 08 02" src="https://user-images.githubusercontent.com/36229929/41648923-83cdf382-747a-11e8-8576-e5e839898627.png">

I have fixed these with commit https://github.com/duality-solutions/Dynamic/commit/4616a34d24d0b4a3a4ba6ee890c3f8ea941810e5:

<strike><img width="403" alt="screen shot 2018-06-20 at 11 11 01" src="https://user-images.githubusercontent.com/36229929/41648984-a50c052a-747a-11e8-9c13-dcb4033592f8.png"></strike>
<strike><img width="699" alt="screen shot 2018-06-20 at 11 10 55" src="https://user-images.githubusercontent.com/36229929/41648985-a52f3784-747a-11e8-92ad-c0c33bbe56c7.png"></strike>
<strike><img width="359" alt="screen shot 2018-06-20 at 11 10 50" src="https://user-images.githubusercontent.com/36229929/41648986-a552a9c6-747a-11e8-8d0f-3d341b650966.png"></strike>

**Comment by LordDarkHelmet** [comment]
Here is the line that specifies the ask to not translate: 
https://github.com/duality-solutions/Dynamic/blob/8869b4e7ec9b727e347c118d344a82500426c895/src/init.cpp#L494

I should have time on Thursday or Friday to fix the final issues. If you find more translation issues just post them to this issue and I will take a look. 

Lol I thought you spoke Korean and were manually translating. I will use Google Translate.

**Comment by LordDarkHelmet** [comment]
All known translation issues are completed. Pull request submitted. I have not culled unused strings yet. That would be a separate task and not part of this issue. 

https://github.com/duality-solutions/Dynamic/commit/dc4254a938e39c95f9387b6b25d5f3f57fa62229
