### ISSUE TITLE
No Genesis Block

### ISSUE THREAD

**Issue by iamnathanwindsor** [duality-solutions/Dynamic#17]
"Incorrect or no genesis block found."

I'm using Mac OS 10.12.6

What should I do?

**Comment by SvenKercher** [comment]
rename the old Roaming/Dynamics or .dynamics folder
because it trys to use the old chain with the new client that has his own chain

**Comment by iamnathanwindsor** [comment]
Thanks! where is that directory and what do I rename it to?

**Comment by SvenKercher** [comment]
User folder

**Comment by iamnathanwindsor** [comment]
Sorry, I don't see it in the hidden library, or my users folder.

**Comment by iamnathanwindsor** [comment]
sorry to ask again, but where is that folder and what should I rename it to?

**Comment by spencerlievens** [comment]
Right-click on Finder icon in dock and select 'Go to Folder':

~/Library/Application Support/

Rename the Dynamic folder to DynamicOld
