### ISSUE TITLE
wallet crash after cpuminer start

### ISSUE THREAD

**Issue by easokol** [duality-solutions/Dynamic#192]
### Describe the issue
Wallet immediately crash when WIP-Dynamic-CPU-Miner start in solo mode
### Steps to reproduce
1. build wallet from any branch
2. build WIP-Dynamic-CPU-Miner
3. add server=1 to conf
4. run wallet, wait for sync finish
5. run cpuminer with params ./cpuminer -a argon2_dyn1 -o http://127.0.0.1:33350 -u <u> -p <p> --no-getwork --coinbase-addr=<addr> -t1
### Expected behavior (tell us what should happen)
miner works properly, wallet is still open and operational
### Actual behavior (tell us what happens instead)
miner says:

[2018-07-31 13:37:03] Long-polling on http://127.0.0.1:33350
[2018-07-31 13:37:03] HTTP request failed: Empty reply from server
[2018-07-31 13:37:03] HTTP request failed: Host name '?e??' contains bad letter
[2018-07-31 13:37:03] json_rpc_call failed, retry after 10 seconds

wallet says:

dynamicd: /usr/include/boost/thread/pthread/recursive_mutex.hpp:118: void boost::recursive_mutex::unlock(): Assertion `!pthread_mutex_unlock(&m)' failed.

no error messages in log, wallet just get stopped
### What platform are you using (Linux, Windows, Mac)
Debian Linux 8, Debian Linux 10

**Comment by SvenKercher** [comment]
WIP miner is not released , WIP = Work in Progress
So we cant say it works or not and also cant support it
But u can use other miners that are available at github and offer argon2d mining
And there are also some pools around

**Comment by easokol** [comment]
I've tried other miners, the same behavior

**Comment by SvenKercher** [comment]
Then ask the other miners, we dont give support on not released stuff

Oh and i know that other miners are working , specially the ones from the pools
U need to look that the argon2 settings are the same in the miner then in the wallet, if they are not the same then u see the wallet crashing

**Comment by easokol** [comment]
If I understand u correctly, this wallet do not support solo mining by external miner at all?

**Comment by easokol** [comment]
My investigates shows that getblocktemplate packet with not empty longpollid value cause a crash.
It's bug in wallet.
Disabling long-poll is work-around

**Comment by easokol** [comment]
Why issue is closed?
When bug will be fixed?

**Comment by SvenKercher** [comment]
Because it is no issue with the wallet
And there is no bug
Getblocktemplate is disabled for some reasons
And the error u send is not related with the wallet, its from an not released repo
Other miners are working
And also only Binaries are supported, because they are tested
The reason is that we cant give support for every self build system with all the possibilies where errors can be hidden (different depends, other installed apps, ...)

**Comment by easokol** [comment]
1. Binary has the same bug (i've just tested the linux binary)
2. It's wallet bug, because the issue take place with all  miners 
3. Who are you if you do not know the difference between Getblocktemplate and getwork?
4. getwork is disabled in your wallet, not Getblocktemplate
5. long-poll cause the crash, not Getblocktemplate
