### ISSUE TITLE
mining with long-poll enabled crash the wallet

### ISSUE THREAD

**Issue by easokol** [duality-solutions/Dynamic#193]
### Describe the issue
any miner with long-poll enabled cause wallet crash with error /usr/include/boost/thread/pthread/recursive_mutex.hpp:118: void boost::recursive_mutex::unlock(): Assertion `!pthread_mutex_unlock(&m)' failed.
### Steps to reproduce
1. run solo mining with long-poll enabled with any miner to any version of wallet (binary release, self-build)
### Do not close, it's bug

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Dynamic/commit/b52d40d74d024f40cc416cdb3e058c820b95aa7f

**Comment by Duality-CDOO** [comment]
@nicknme i have made changes and if you want to test, you are welcome to.
