### ISSUE TITLE
DYN Block Rejected

### ISSUE THREAD

**Issue by goodthebest** [duality-solutions/Dynamic#195]
@AmirAbrams @SvenKercher @spencerlievens 

### Describe the issue
Block rejected, I used RPC encoding POW
Is there any other special configuration needed such as Dev fee etc?

### Steps to reproduce
1. Used yiimp 
https://github.com/duality-solutions/yiimp

2. yiimp also showing wrong block reward

![image](https://user-images.githubusercontent.com/1715740/43902831-1b69501c-9bfc-11e8-9e7a-372d83e96428.png)

### Expected behavior (tell us what should happen)
- Block should be accepted
- yiimp should also show correct block reward

### Actual behavior (tell us what happens instead)
- block being rejected
- incorrect block reward info

### Screenshots
![image](https://user-images.githubusercontent.com/1715740/43901363-5671da02-9bf8-11e8-84da-8d0bbd2e1f4f.png)

### debug.log from DYN daemon

2018-08-09 12:59:12 CDynodeBlockPayees::IsTransactionValid -- ERROR: Missing required payment, possible payees: 'DJRG5eTJey8khFczxzSZ4bezA5H1dwSkVD', amount: 1.618000 DYN
2018-08-09 12:59:12 IsBlockPayeeValid -- ERROR: Invalid Dynode payment detected at height 153948: CTransaction(hash=b5dacc3376, ver=2, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 035c5902048a3a6c5b088100000b000000007969696d7000, nSequence=0)
    CTxOut(nValue=2.61800000, scriptPubKey=76a9142b05fcaa3334b5dd4a0398d3)
2018-08-09 12:59:12 ERROR: ConnectBlock(DYN): couldn't find Dynode or Superblock payments
2018-08-09 12:59:12 InvalidChainFound: invalid block=00000000d73334ec62cf48418e17a45c301f8b45df225b0f855f1515b9f700d2  height=153948  log2_work=48.022715  date=2018-08-09 12:58:50
2018-08-09 12:59:12 InvalidChainFound:  current best=0000000049d372e9057b5beacaca1063c42142d73283ae36a6f40d13589c2b54  height=153947  log2_work=48.022695  date=2018-08-09 12:58:49
2018-08-09 12:59:12 ERROR: ConnectTip(): ConnectBlock 00000000d73334ec62cf48418e17a45c301f8b45df225b0f855f1515b9f700d2 failed
2018-08-09 12:59:12 InvalidChainFound: invalid block=00000000d73334ec62cf48418e17a45c301f8b45df225b0f855f1515b9f700d2  height=153948  log2_work=48.022715  date=2018-08-09 12:58:50

### What platform are you using (Linux, Windows, Mac)
linux

**Comment by goodthebest** [comment]
@AmirAbrams yes I used yiimp's argon2d-test branch.

I was mining on mainnet and got block rejected 

>  add some Dynodes and run some fluid commands

What are those steps, could you please give details

**Comment by goodthebest** [comment]
@AmirAbrams another thing what RPC encoding you are using in yiimp Daemon tab, **POW** or **POW**

I tried with **POW** and got block rejected

**Comment by goodthebest** [comment]
@AmirAbrams 
these are my yiimp tab configurations, could you please advise if anything needs to be checked/unchecked or any input misisng?

## SETTINGS tab
![image](https://user-images.githubusercontent.com/1715740/43928147-e8301092-9c40-11e8-8d5f-d15decd41c39.png)

## DAEMON tab
![image](https://user-images.githubusercontent.com/1715740/43928184-09eb44b8-9c41-11e8-9b71-b08815c32a96.png)

**Comment by goodthebest** [comment]
@AmirAbrams Still getting rejected blocks and waiting for your feedback I've posted screenshots and also debug log too. I've tried both POW and POS as rpc encoding. It seems there is something missing that needs to be done?

**Comment by goodthebest** [comment]
@AmirAbrams @Duality-CDOO 
hey guys no word?

**Comment by AmirAbrams** [comment]
@goodthebest, our daemon tab settings look the same.

On the settings tab, after the last commit, I get the correct Dynode reward amount but the block is 0 on the pool page even when the daemon is fully synced on mainnet:
![stratum-dynamic-mining-pool](https://user-images.githubusercontent.com/7564876/44134879-46e9d688-a02c-11e8-93cb-7e31d1a6cd1f.png)

It shows the correct block on the coin admin page:
![stratum-dynamic-coin](https://user-images.githubusercontent.com/7564876/44135085-24b4ece6-a02d-11e8-8908-64881e506e5b.png)

Shares are accepted unlike before the last commit:

`
2018-08-15 06:27:17 ProcessNewBlock : ACCEPTED
2018-08-15 06:27:17 CDynodePayments::FillBlockPayee: Dynode payee found.
2018-08-15 06:27:17 CDynodePayments::FillBlockPayee -- Dynode payment 1.618 to DLa4xVGeojdxk7Lwz5nytv5paY2RUb9w5F
2018-08-15 06:27:17 CreateNewBlock(): total size 1000 txs: 0 fees: 0 sigops 100
2018-08-15 06:27:17 CreateNewBlock(): Computed Miner Block Reward is 1.00 DYN
2018-08-15 06:27:45 CDynodeMan::CheckAndRemove
`

The Yiimp coin settings tab is showing the correct reward amount:
![stratum-wallet-settings](https://user-images.githubusercontent.com/7564876/44134315-f9d804d4-a029-11e8-86a7-d520bfc435c3.png)

please pull from our [argon2d-dynamic yiimp](https://github.com/duality-solutions/yiimp/tree/argon2d-dynamic) repo branch and try again.

I have not found a block so can not confirm it is working for sure.  The stratum pool address is https://stratum.dualityblocks.com

**Comment by AmirAbrams** [comment]
@goodthebest, I made some fixes and the default branch for our [yiimp](https://github.com/duality-solutions/yiimp) repo has been tested and deployed on two mining pools:
https://miningpatriot.com
https://rignrack.com/

Testnet pool: https://testpool.dualityblocks.com

**Comment by goodthebest** [comment]
@AmirAbrams thanks for the update. 

Is **add-argon2d-dynamic** is correct branch?

**Comment by movebtch** [comment]
He mr u hide behind screen nogoodyiusuck you fu k this guy too or at least try, I warned you man I'm not everyone else I won't stop. So you may as well just go away you ain't no coder you are a common fucking thief. You know it and any mother tucker who wants to ask me questions I'm answer them you are trash chicken shit piece of crap. So until myself or the FBI finds you I see them this week you better pack it up pack it in hope the us feds find you before I do. I'm not fuckingplaying with you I'm posting this shot everywhere until you grow so e balls and call me or face dude. I have nothing but time butch.
