### ISSUE TITLE
Hard Fork Causes Headers Validation Failure

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#212]
### Describe the issue
When trying to sync with a new data directory, the local node starts to ban all others due to this error:
```
ERROR: ContextualCheckBlockHeader : incorrect proof of work at 300001
Misbehaving: 149.202.44.104:31300 (0 -> 100) BAN THRESHOLD EXCEEDED
ERROR: invalid header received 00000a6408685e1d7b11729bd81da982a26..
ProcessMessages(headers, 144102 bytes) 
FAILED peer=902017-04-08 21:22:22 ThreadSocketHandler 
-- removing node: peer=90 addr=149.202.44.104:31300 
nRefCount=1 fNetworkNode=1 fInbound=0 fDynode=0
```
### Steps to reproduce
1. Clear Blockchain files in data directory.
2. Start Dynamic wallet (Daemon or Qt).
3. Wait until the headers sync process gets to block 300,001 (hard fork block where the difficulty algorithm was changed).
### Expected behavior (tell us what should happen)
Block 300,001 should be accepted and not cause banning and not prevent chain syncing.
### Actual behavior (tell us what happens instead)
The node rejects the header for block 300,001 and bans all good nodes, preventing the chain download.
### Screenshots
![dynamic-ban-issue](https://cloud.githubusercontent.com/assets/7564876/24836028/f4f45c74-1cd6-11e7-8503-c91aa48a9425.png)
### What platform are you using (Linux, Windows, Mac)
Tested with Ubuntu 16.04 and Windows Server 2016.  Tested with version 1.3.0.1 and 1.4.0.0

**Comment by plaxton** [comment]
Resolved in v1.3.2.0
