### ISSUE TITLE
DNSseeder only  pulls the IP of the DNS Seeder itself

### ISSUE THREAD

**Issue by SvenKercher** [duality-solutions/Dynamic#222]
### Describe the issue
DNSseeder only  pulls the IP of the DNS Seeder itself, no query for seeded nodes

### Steps to reproduce
1. 
2. 
3. 
### What platform are you using (Linux, Windows, Mac)

**Comment by LordDarkHelmet** [comment]
Nice catch. That explains why the current batch of users have stalled after the bootstrap import.

**Comment by Duality-CDOO** [comment]
I have overhauled the entire netcode of the wallet and it still does the same, maybe it is in fact the dnsseeder.

**Comment by Duality-CDOO** [comment]
@SvenKercher fixed?
