### ISSUE TITLE
cannot interact via RPC with dynamicd for first start on clean install

### ISSUE THREAD

**Issue by beralt85** [duality-solutions/Dynamic#226]
### Describe the issue
On a new install, `dynamicd` starts, creates a `dynamic.conf` with random credentials, but then cannot be reached using the client `dynamic-cli` because the newly created credentials are not accepted.
Hence, one has to kill `dynamicd` and start it again. This is unconvenient.

### Steps to reproduce
1. start daemon `dynamicd` with clean data directory
2. try to interact it with the client `dynamicd`

### Expected behavior (tell us what should happen)
One should be able to interact with the daemon directly after the first start.
We had the same with sequence. There we fixed it, as I recall.

### What platform are you using (Linux, Windows, Mac)
all platforms

**Comment by SCDeveloper** [comment]
Upon initial start of dynamicd it looks for a conf file and creates if it is not present., however, this means that dynamicd isn't using the newly created dynamic.conf file until restart. Not sure if this is an issue, or not.

**Comment by plaxton** [comment]
What we could do is that the client terminates with a message prompting to restart the client due to the generation of the file, therefore - prompting the user to restart, this isn't an issue but could be a feature as the daemon isn't supposed to be used by most end-users

**Comment by spencerlievens** [comment]
https://github.com/duality-solutions/Dynamic/commit/accfd8756d49f84f482cb2a4727b708890c519ad
