### ISSUE TITLE
Compile fail on raspberry: #include <emmintrin.h>

### ISSUE THREAD

**Issue by beralt85** [duality-solutions/Dynamic#24]
### Describe the issue
DarkSilk-Core does not build on R-Pi.
Make fails with:
```  CC       crypto/argon2d/crypto_libdarksilk_crypto_a-opt.o
In file included from crypto/argon2d/opt.c:26:0:
crypto/argon2d/opt.h:25:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
Makefile:3824: recipe for target 'crypto/argon2d/crypto_libdarksilk_crypto_a-opt.o' failed
make[2]: *** [crypto/argon2d/crypto_libdarksilk_crypto_a-opt.o] Error 1
make[2]: Leaving directory '/home/pi/DarkSilk-Core/src'
Makefile:8521: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/DarkSilk-Core/src'
Makefile:640: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
Am I missing some package?

I found these related bugs for another coin:
https://github.com/barrysteyn/node-scrypt/issues/44
https://forum.duniter.org/t/i-have-trouble-installing-ucoin-on-an-arm-computer/245

### What platform are you using (Linux, Windows, Mac)
R-Pi, Raspbian

**Comment by spencerlievens** [comment]
Looks like I am buying a Rasp-Pi for build testing :P

**Comment by beralt85** [comment]
I think it has to do with the CPUID on ARM chipsets. Here is some more info:
http://www.rtsoft.com/forums/showthread.php?55599-Raspberry-Pi-Compilation

**Comment by GregoryBetz** [comment]
That does look like an interesting project. I think even with the power of mobile cpus now phones would be able to be stormnodes without getting overly hot. Maybe. If so it would be pretty awesome.

**Comment by GregoryBetz** [comment]
In the skype group yesterday we discussed that this issue and found that Raspberry pie is incompatible with our PoW algorithm. Closing this issue as it is now resolved.

**Comment by beralt85** [comment]
Can you then add a configure option that disables the capability of POW mining, but still allows me to use a DarkSilk Wallet (and, more importantly: run Stormnodes) on a Raspi?

**Comment by GregoryBetz** [comment]
Yes, this was considered and determined that it would still not be possible, but I'll take a closer look at the code and see if Blake (which has functions requiring the 128 bit registers that are incompatible with RasPi) is used anywhere else, as this could be a possible work around. Maybe you could try completely removing the crypto files and see if it is just a matter of removing them or if a more involved solution is needed.

**Comment by coin-info-net** [comment]
Argon2d use SSE2 commands
ARM CPUs dont support that
So atm its not possible to use DYN on an Raspberry Pi

**Comment by Ieathan** [comment]
:'(

@coin-info-net are you implying arong2i may work?
