### ISSUE TITLE
Not getting any peers, added nodes to config file and firewall is disabled

### ISSUE THREAD

**Issue by SvanZui** [duality-solutions/Dynamic#25]
using the windows wallet and added the noded to the config file but only get connecting to peers for hours
config file

#Do not use special characters with username/password
rpcuser=HidbVZwrpw
rpcpassword=kQEZEXEv5VHQjKgvFSH
rpcport=32350
port=32300
addnode=134.3.76.188:32300
addnode=35.205.91.111:32300
addnode=35.196.201.112:32300
addnode=83.46.213.252:32300
addnode=82.73.162.116:32300
addnode=134.3.76.188:32300
addnode=173.208.242.179:49450
addnode=93.77.160.162:51142
addnode=158.69.120.22:39552
addnode=216.75.121.174:51545
addnode=92.112.166.63:52488
addnode=158.69.122.63:52244
addnode=54.173.15.232:44316
addnode=95.90.216.53:35668
addnode=176.58.207.76:26643

**Comment by lleellee0** [comment]
These nodes seem to be saturated. Because these nodes are not " special ", they can use the IP address of another node(miner).

Like

addnode=199.195.116.166:32300

This is one of my miner. Give it try and tell me.

**Comment by SvanZui** [comment]
thanks, that worked 👍
