### ISSUE TITLE
Fix GetWork Mining RPC Command

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#26]
### Describe the issue
getwork doesn't work.  causes the wallet to segfault.
### Steps to reproduce
1. Run the wallet with RPC and listening on
2. Run CPU miner
3. When the miner finds a block and submits it, the wallet crashes.
### Expected behavior (tell us what should happen)
After finding a block with getwork, it should be accepted.
### What platform are you using (Linux, Windows, Mac)
Linux Ubuntu 16.04 64-bit.

**Comment by SCDeveloper** [comment]
https://github.com/duality-solutions/Dynamic/commit/8355d45cddd58c4ba19dde1789fbb41bbc5f1505 - Under TestNet

**Comment by SCDeveloper** [comment]
https://github.com/duality-solutions/Dynamic/commit/c77d2289f6ce7d53d93160408f28731308b7584a
