### ISSUE TITLE
Confirmations do not update on CoinControlDialog if left open.

### ISSUE THREAD

**Issue by Duality-CDOO** [duality-solutions/Dynamic#260]

**Comment by Duality-CDOO** [comment]
This isn't a bug, but would be nice for coincontrol to update periodically.

**Comment by SvenKercher** [comment]
Confirmations would require a update of the raw data that is pulled from the coin select window, and this would also cause a reset of all selected inputs

Would work if the blocks are timed like at BTC with 15+ minutes, so ppl have enough time to select all what they want , but with our fast blocks it would update faster then ppl could select their inputs
