### ISSUE TITLE
RPC commands need to be added/updated

### ISSUE THREAD

**Issue by GregoryBetz** [duality-solutions/Dynamic#31]
### Describe the issue
We need to remove gobject and replace it with the updated rpc functions for budget blocks. The documentation we currently have does not correlate with the actual rpc command(s) in the wallet.

**Comment by spencerlievens** [comment]
Updated functions for budget blocks? We are working off of Dash 0.12.1.x which is ahead of their Master. I don't believe there are any further updated functions.

**Comment by GregoryBetz** [comment]
sentinel will help
