### ISSUE TITLE
The variable 'data_independent_addressing' is being used without being initialized.

### ISSUE THREAD

**Issue by cdii** [duality-solutions/Dynamic#314]
https://github.com/duality-solutions/Dynamic/blob/eedf9b29b3a1904274ad3681f762a0d82d881ecc/src/crypto/argon2d/opt.c#L188

**Comment by AmirAbrams** [comment]
@daffybunny , thanks for reporting this.  

This commit should resolve the issue: https://github.com/duality-solutions/Dynamic/commit/5f655a76c4396b2009a0231346e11d619d566f9c

I ported the code from the original Argon2 repo here: https://github.com/P-H-C/phc-winner-argon2/blob/e4ca309b044fdc6ec547a3e1a106b4bfd06563b4/src/opt.c#L194

**Comment by AmirAbrams** [comment]
fixed in version 2.4
