### ISSUE TITLE
Fix dncache.dat file

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#387]
### Describe the issue
The dncache.dat file gets corrupt and needs to be deleted after several restarts to see an accurate Dynode network status.
### Steps to reproduce
1. Open the Dynamic wallet and let it fully sync.
2. Run the fully synced wallet for 8 hours or more
3. Close the Dynamic wallet
4. Repeat steps 1-3 several times
### Expected behavior (tell us what should happen)
Accurate Dynode network status without deleting the dncache.dat
### What platform are you using (Linux, Windows, Mac)
Testing on Ubuntu 18 and Ubuntu 16

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Dynamic/commit/f29894f2ef03dc0807742caa73fadd582d0e0208
