### ISSUE TITLE
undefined/uninitialized variable showing up in gui

### ISSUE THREAD

**Issue by chlorocryptos** [duality-solutions/Dynamic#391]
### Describe the issue
in the sync progress bar a variable name %n shows up stating
' %n second(s) behind'
the same %n appears in the corresponding tooltip (see screenshot)
probably it's harmless, but looks odd anyway...

### Steps to reproduce
1. Open the Dynamic wallet and let it fully sync.
2. Either the issue shows up directly on last blocks to sync or after full sync, shutdown and re-open of client

### Expected behavior (tell us what should happen)
either the remaining seconds are properly shown or left out completely

### Actual behavior (tell us what happens instead)
an empty variable with its variable name (?) is shown

### Screenshots
![dynamic_2_4_1_undefined_variable](https://user-images.githubusercontent.com/53777918/67846199-15c0b280-fb01-11e9-9d10-b0d44c70049d.jpg)

### What platform are you using (Linux, Windows, Mac)
windows 7 64 bit

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Dynamic/pull/392/files

Requires testing @chlorocryptos if you are able to test.

I couldn't replicate your UI experience.

**Comment by Duality-CDOO** [comment]
@chlorocryptos can you confirm if you see %n only in the last 60 seconds of sync, or is during the entire process?

**Comment by chlorocryptos** [comment]
the '%n second(s) behind' appeared only at the end of the sync, apparently if really only seconds were left to complete the sync. before, the 'hours and minutes behind' were shown correctly. 
since this first occurrences i've shutdown and re-opened the client (v 2.4.1.0 and now v 2.4.3.0) several times, but was not able to replicate the issue. there were always minutes shown left to completion and then the gui switched to sync completion.
i've tried to replicate the issue by observing the last added block via the block explorer and the system time:
if the last added block was within ~10 s of sytem time i had opened the gui.
but most of the time block delay and opening of the gui (block loading and establishing peer connections) took more than a minute, so the gui sync never showed the last block within a minute.     
so probably this issue arose out of  a quite rare constellation and is tricky to replicate...
also, in the moment the network difficulty appears to be quite high, so probably chances to observe
the issue are better when block succession is faster.
if i stumble across another occurrence of this issue (now with the updated v2.4.3.0 client) i will post a screenshot...

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Dynamic/commit/0a236d23059222ce51da764ee42cccb79cd8bd5d
