### ISSUE TITLE
No calculation of BDAP fee when balance is 0

### ISSUE THREAD

**Issue by SvenKercher** [duality-solutions/Dynamic#393]
### Describe the issue
Create BDAP account with a wallet balance of 0
Then no calculation is shown how much u have to add to your wallet
It only gives back "insufficient amount"

So u dont know how much u have to charge your wallet to create a BDAP account

### Steps to reproduce
1. 
2. 
3. 
### What platform are you using (Linux, Windows, Mac)

**Comment by AmirAbrams** [comment]
Pull request https://github.com/duality-solutions/Dynamic/pull/399 addresses this issue.

**Comment by Duality-CDOO** [comment]
Works.
