### ISSUE TITLE
"dynode list-conf" shows only the last entry of dynode.conf

### ISSUE THREAD

**Issue by SvenKercher** [duality-solutions/Dynamic#397]
### Describe the issue
"dynode list-conf" shows only the last entry of dynode.conf

### Steps to reproduce
1. open debug console and enter "dynode list-conf"

### Expected behavior (tell us what should happen)
should show all dynode entries within the dynode.conf file

### Actual behavior (tell us what happens instead)
shows only the last entry in the dynode.conf file

### What platform are you using (Linux, Windows, Mac)

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Dynamic/commit/10c880a8b1c993c01b5198ba5e01f0656835281e

Requires testing.
