### ISSUE TITLE
Miner thread segfault at shutdown

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Dynamic#7]
void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.
bash: line 40: 14024 Aborted                 (core dumped)

**Comment by spencerlievens** [comment]
Cannot replicate on OSX.

**Comment by ghost** [comment]
Can be replicated on Ubuntu 16.04

**Comment by spencerlievens** [comment]
boost::asio issue, cannot locate it, shutdown order issue

**Comment by spencerlievens** [comment]
@AmirAbrams can you test v2.1-WIP branch and see if this fault is now gone please.
